version: "3.8"


services:
  prometheus:
    image: prom/prometheus
    ports:
      - 9090:9090
    volumes:
      - ./configs/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./prometheus:/prometheus
      
  grafana:
    build: './configs/grafana'
    ports:
      - 3000:3000
    volumes:
      - ./grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=admin
    depends_on:
      - prometheus
      
  mysql-server:
    image: mysql:latest
    expose:
        - "3306"
    ports:
        - "3306:3306"
    command: --init-file /database/init.sql
    volumes:
        - ./database/init.sql:/database/init.sql
    environment:
        MYSQL_ROOT_USER: root
        MYSQL_ROOT_PASSWORD: root
      
  file-storage-server:
    container_name: web-file-storage
    build: web-file-storage/
    ports:
        - "8081:8081"
    stdin_open: true # docker run -i
    tty: true # docker run -t
    depends_on:
      - mysql-server
